server:
  port: 9005

custom:
  server-ip: localhost

spring:
  application:
    name: CONFIG-SERVICE
  boot:
    admin:
      client:
        url: http://${custom.server-ip}:8762
        instance:
          service-base-url: http://${custom.server-ip}:${server.port}
          name: ${spring.application.name}
  profiles:
      active: native
  cloud:
      config:
          server:
              native:
                  search-locations: "classpath:/config"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${custom.server-ip}:8761/eureka/
  instance:
    hostname: ${custom.server-ip}
    prefer-ip-address: true
    ip-address: ${custom.server-ip}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    pause:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true


